wandb:
  project: default
  name: ''
  enable: False

debug: false
datapath: /work/log1/chendi.qian/qp_400_new
runs: 1
losstype: l2
ckpt: true
lr: 1.e-3
weight_decay: 0.
epoch: 1000
patience: 100
batchsize: 32
val_batchsize: 128
coeff_obj: 1.
coeff_vio: 1.

eval_every: 1
tripartite: false
conv: gcnconv
gat:
  heads: 1
  concat: false
hidden: 128
num_encode_layers: 2
num_conv_layers: 8
num_pred_layers: 2
hid_pred: -1
num_mlp_layers: 1
norm: graphnorm